version: '3.7'

services:
  web:
    build: ./app
    command: gunicorn my_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    networks:
      - app-network

volumes:
  postgres_data:

#Docker Networks
networks:
  app-network:
    driver: bridge
